---
- name: create alertmanager system group
  group:
    name: alertmanager
    system: true
    state: present

- name: create alertmanager system user
  user:
    name: alertmanager
    system: true
    shell: "/usr/sbin/nologin"
    group: alertmanager
    createhome: false

- name: create alertmanager directories
  file:
    path: "{{ item }}"
    state: directory
    owner: alertmanager
    group: alertmanager
    mode: 0755
  with_items:
    - "{{ alertmanager_config_dir }}"
    - "{{ alertmanager_config_dir }}/templates"
    - "{{ alertmanager_db_dir }}"

- name: download alertmanager binary to local folder
  become: false
  get_url:
    url: "{{ binary_url }}"
    dest: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"

- name: unpack alertmanager binaries
  become: false
  unarchive:
    src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    creates: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64/alertmanager"

- name: propagate official alertmanager and amtool binaries
  copy:
    src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: "0755"
    owner: root
    group: root
  with_items:
    - alertmanager
    - amtool
  notify:
    - restart alertmanager