---
- name: copy prometheus alerting rules
    src: "{{ item }}}}"
    dest: "{{ prometheus_config_dir }}/"
    owner: root
    group: prometheus
    mode: 0640
    validate: "{{ prometheus_binary_install_dir }}/promtool check rules %s"
  with_fileglob: "{{ prometheus_rule_files }}"
  notify:
    - reload prometheus

- name: Generate configuration file of prometheus
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    force: true
    owner: root
    group: prometheus
    mode: 0640
    validate: "{{ prometheus_binary_install_dir }}/promtool check config %s"
  notify:
    - reload prometheus